In [4]:
"Contacted Leads -> Converted Customers"

'Contacted Leads -> Converted Customers'

In [ ]:
# ===== Full Clean Random Forest Training =====

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

# Load data
df = pd.read_csv("../data/raw/bank_marketing.csv", sep=",", engine="python")

# Encode target
df['deposit'] = df['deposit'].map({'yes': 1, 'no': 0})

# Split features & target
X = df.drop('deposit', axis=1)
y = df['deposit']

# One-hot encoding
X = pd.get_dummies(X, drop_first=True)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Train Random Forest
rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

rf_model.fit(X_train, y_train)

print("Model successfully trained.")

Model successfully trained.

In [ ]:
feature_importance = pd.Series(
    rf_model.feature_importances_,
    index=X_train.columns
).sort_values(ascending=False)

feature_importance.head(10)

duration            0.337902
balance             0.083896
age                 0.077881
day                 0.071932
campaign            0.036946
poutcome_success    0.036258
pdays               0.034531
contact_unknown     0.032653
housing_yes         0.026965
previous            0.020153
dtype: float64

In [ ]:
X_no_leak = X.drop('duration', axis=1)

In [ ]:
pd.crosstab(df['housing'], df['deposit'], normalize='index') * 100

deposit          0          1
housing
no       42.968883  57.031117
yes      63.359212  36.640788

In [ ]:
pd.crosstab(df['loan'], df['deposit'], normalize='index') * 100

deposit          0          1
loan
no       50.474129  49.525871
yes      66.849315  33.150685

In [6]:
import pandas as pd
from sklearn.model_selection import train_test_split

df = pd.read_csv("../data/raw/bank_marketing.csv", sep=",", engine="python")
df['deposit'] = df['deposit'].map({'yes': 1, 'no': 0})

X = df.drop('deposit', axis=1)
y = df['deposit']

X = pd.get_dummies(X, drop_first=True)

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [7]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

rf_model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

In [8]:
feature_importance = pd.Series(
    rf_model.feature_importances_,
    index=X_train.columns
).sort_values(ascending=False)

feature_importance.head(10)

duration            0.337902
balance             0.083896
age                 0.077881
day                 0.071932
campaign            0.036946
poutcome_success    0.036258
pdays               0.034531
contact_unknown     0.032653
housing_yes         0.026965
previous            0.020153
dtype: float64

In [ ]:
import joblib
joblib.dump(rf_model, "../models/random_forest.pkl")

# 📌 Period 4 – Business Insights & Funnel Optimization

## 🎯 Objective

Translate model outputs into actionable business insights to improve marketing performance and lead conversion.

---

## 🔍 Funnel Analysis

Marketing Funnel:

Contacted Leads → Converted Customers

Key Drop-Off Identified:

- Unknown contact channel shows significantly lower conversion rate.
- Cellular contact method performs best.

---

## 📊 Conversion Drivers

Top influential features identified using Random Forest:

- Contact type  
- Campaign frequency  
- Previous campaign outcome  
- Customer financial attributes  

⚠ Call duration was identified as a strong predictor but represents data leakage, as it is known only after contact is made.

---

## 💼 Business Recommendations

1. Increase investment in high-performing contact channels (Cellular).
2. Reduce dependency on low-performing unknown contact methods.
3. Implement lead scoring before outreach.
4. Limit excessive repeated calls.
5. Target customer segments with historically higher conversion probability.

---

## 📈 Strategic Impact

Using predictive modeling for lead prioritization can:

- Improve marketing ROI  
- Reduce outreach cost  
- Increase conversion efficiency  
- Optimize campaign strategy  

---

## 🚀 Final Phase – Period 5

Next, we will:

- Clean repository structure  
- Finalize README  
- Prepare resume-ready description  
- Polish project for GitHub presentation